camera_base:
  num_sensors: 1

  # note that the image is in shape(num_envs, num_sensors, height, width)
  height: 96
  width: 128
  horizontal_fov_deg: 90.0
  max_range: 10.0
  min_range: 0.2

  calculate_depth: True
  return_pointcloud: False

  pointcloud_in_world_frame: False

  camera_extrinsics:  
    translation: [0.27, 0.0, 0.03]    # x, y, z
    # rotation: [0, 0.5,0, 0.866]  # quaternion [x, y, z, w]
    rotation: [0, 30, 0]           # euler [roll, pitch, yaw]

    trans_rad :
      min: [-0.0, -0.0, -0.0]  # x, y, z
      max: [0.0, 0.0, 0.0]     # x, y, z
    rot_rad : 
      min: [-0.0, -2, -0.0]  # r p y radians
      max: [0.0, 2, 0.0]     # r p y radians


img_process:
  # resize: [400, 400]        # height width
  noise: 
    gaussian: 0.1           # mean
    dropout: 0.1            # probability
  clip: [0.0, max_range]    # min, max
  normalize: True           # return real depth or [0, 1] normalized depth  512 env -> 800mb

terrain_process:
  offset: False